---
title: "Testing markdown"
author: "Gurudev Ilangovan"
date: "February 28, 2017"
output: html_document
---

```{r}

inp = read.csv("./data/demo1.csv")
inp = cvt_seq(inp,pd=1)
weighted_seq = align_multiple_sequences(inp)
weighted_seq$n = NULL


```

```{r}
ws <- "< (E:1, L:1, R:1, T:1, V:1, d:1) (A:1, B:9, C:8, D:8, E:12, F:1, L:4, P:1, S:1, T:8, V:5, X:1, a:1, d:10, e:2, f:1, g:1, p:1) (B:99, C:96, D:91, E:24, F:2, G:1, L:15, P:7, R:2, S:8, T:95, V:15, X:2, Y:1, a:2, d:26, e:3, g:6, l:1, m:1) (A:5, B:16, C:5, D:3, E:13, F:1, H:2, L:7, P:1, R:2, S:7, T:6, V:7, Y:3, d:3, g:1) (A:13, B:126, C:27, D:1, E:32, G:5, H:3, J:1, L:1, R:1, S:32, T:21, V:1, W:3, X:2, Y:8, d:13, e:1, f:8, i:2, p:7, l:3, g:1) (A:12, B:6, C:28, D:1, E:28, G:5, H:2, J:6, L:2, S:137, T:10, V:2, W:6, X:8, Y:124, a:1, d:6, g:2, i:1, l:1, m:2) (A:135, B:2, C:23, E:36, G:12, H:124, K:1, L:4, O:2, R:2, S:27, T:6, V:6, W:10, X:3, Y:8, Z:2, a:1, d:6, g:1, h:2, j:1, k:5, l:3, m:7, n:1) (A:11, B:1, C:5, E:12, G:3, H:10, L:7, O:4, S:5, T:1, V:7, W:3, X:2, Y:3, a:1, m:2) (A:31, C:15, E:10, G:15, H:25, K:1, L:7, M:1, O:1, R:4, S:12, T:10, V:6, W:3, Y:3, Z:3, d:7, h:3, j:2, l:1, n:1, p:1, q:1) (A:3, C:5, E:4, G:7, H:1, K:1, R:1, T:1, W:2, Z:2, a:1, d:1, h:1, n:1) (A:20, C:27, E:13, G:35, H:7, K:7, L:111, N:2, O:1, Q:3, R:11, S:10, T:20, V:111, W:2, X:2, Y:3, Z:8, a:1, b:1, d:13, h:9, j:1, n:1, o:2) (A:17, B:2, C:14, E:17, F:1, G:31, H:8, K:13, L:2, M:2, N:1, R:22, S:2, T:140, U:1, V:2, W:2, X:1, Z:13, a:1, b:8, d:6, h:14, n:6, p:1, q:1) (A:12, B:7, C:5, E:13, G:16, H:5, K:106, L:8, N:2, O:1, R:32, S:3, T:29, V:9, X:2, Z:9, b:16, c:5, d:5, h:7, l:1) (A:7, B:1, C:9, E:5, G:7, H:3, K:7, R:8, S:1, T:10, X:1, Z:3, a:2, b:3, c:1, d:5, h:3) (A:1, B:1, H:1, R:1, T:1, b:2, c:1) (A:3, B:2, C:2, E:6, F:2, G:4, H:2, K:20, M:2, N:3, R:19, S:3, T:11, U:2, X:4, Z:34, a:3, b:11, c:2, d:4) (H:1, Y:1, a:1, d:1) >"
n=162

ws2 = strsplit(ws, split = "[\\(*)]",fixed = F)[[1]]
ws2 = ws2[!(ws2 %in% c(" >", " ", "< "))]
ws3 = strsplit(ws2, split = ", ")
ws3
ws4 = reshape2::melt(ws3)
ws4$value = as.character(ws4$value)
ws4$element = vapply(ws4$value, function(x) strsplit(x,split = ":")[[1]][1], FUN.VALUE = "character")
ws4$ele_Weight = vapply(ws4$value, function(x) strsplit(x,split = ":")[[1]][2], FUN.VALUE = "character")
ws4$ele_Weight = as.numeric(ws4$ele_Weight)
ws4$Cluster = 1

ws5 <- ws4 %>% select(Cluster, "Itemset" = L1, element, ele_Weight)



(freq_plot <- ws5 %>% mutate(element_number = 1:nrow(ws5)) %>%
  ggplot(aes(x = element_number, y = ele_Weight, text = element)) +
  geom_point(size = 0.75) +
  geom_path(group = 1, size=0.1) +
  geom_hline(yintercept = 60) +
  geom_label(aes(label = element,size = ele_Weight)))



```

